blog/urls.py
from django.urls import path
from blog.views import *
from blog.feeds import LatestEntriesFeed
app_name = 'blog'

urlpatterns = [
    path('<int:pid>' , blog_single_views , name = 'blog-single'),
    path('category/<str:blog_category>' , blog_home_views , name = 'category'),
    path('' , blog_home_views , name = 'blog-home'),
    path('author/<str:username_author>', blog_home_views ,name =  'author'),
    # path('test' , test , name='test'),
    path('search/' , blog_search , name = 'search'),
    path( 'rss/feed/' ,LatestEntriesFeed())
]

index/urls.py
from django.urls import path
from index.views import *
from blog.views import blog_home_views

app_name = 'website'

urlpatterns = [
    path('' , index_views , name="index"),
    path('about/' , about_views , name="about"),
    path('contact/' , contact_views , name="contact"),
    path('category/<str:blog_category>' , blog_home_views , name = 'category'),
    path('newsletter' , news_letter_view , name = 'newsletter'),
    # path('elements/' , elements_views , name="element"),
    # path('robots.txt', robots_txt, name='robots_txt'),
    
]

mysite/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from index.sitemaps import StaticViewSitemap
from blog.sitemaps import BlogSitemap
from index.views import *
from blog.views import *
from debug_toolbar.toolbar import debug_toolbar_urls

sitemaps = {
    "static": StaticViewSitemap,
    'blog': BlogSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include('index.urls')),
    path('blog/' , include('blog.urls')),
    path('accounts/' , include('account.urls')),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",),
    
        path('robots.txt', include('robots.urls')),
        path('summernote/', include('django_summernote.urls')),
        path('captcha/', include('captcha.urls')),
         
    
]
urlpatterns += debug_toolbar_urls()


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=255)
    
    def __str__(self) -> str:
        return self.name
    
class BlogPost(models.Model):
    title =  models.CharField(max_length=100)
    content = models.TextField()
    author = models.ForeignKey(User , on_delete=models.SET_NULL , null=True)
    category = models.ManyToManyField(Category)
    image_filed = models.ImageField(upload_to='blog/' , default='/blog/feature-img1.jpg')
    counted_view = models.IntegerField(default=0)  #(default=0)
    login_require = models.BooleanField(default=False)
    status = models.BooleanField(default=False)
    create_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    published_date = models.DateTimeField(null=True)
    tags = TaggableManager()
    
    
    def __str__(self) -> str:
        return " {} - {}".format(self.title , self.id)
    
    def get_absolute_url(self):
        return reverse('blog:blog-single', kwargs={'pid':self.id})

    class Meta:
        db_table_comment = "Question answers"
        
class Comment(models.Model):
    post = models.ForeignKey(BlogPost, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    email = models.EmailField()
    subject = models.CharField(max_length=255)
    message = models.TextField()
    approved = models.BooleanField(default=False)
    create_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    
    
    class Meta:
        ordering = ['-create_date']
    def __str__(self):
        return " {}".format(self.subject)
    
        

blog/forms.py
from django.forms import ModelForm
from captcha.fields import CaptchaField
from blog.models import Comment

class CommentForm(ModelForm):
    # captcha = CaptchaField()
    
    class Meta:
        model = Comment
        fields = ['post', 'name' , 'email' , 'subject' , 'message']

blog/views.py
from django.shortcuts import render , get_object_or_404  , redirect 
from blog.models import BlogPost , Comment
from django.http import Http404
from django.urls import reverse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from blog.forms import CommentForm
from django.contrib import messages

# Create your views here.

def blog_single_views(request,pid):
    
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Dear comment submission successful' )
        else:
            messages.error(request, 'Dear comment submission Wrong' )
   
    
    posts = BlogPost.objects.get(pk=pid , status=1)
    if posts.login_require:
         
        comment = Comment.objects.filter(post=posts.id,approved=True)
        form = CommentForm()
        context = {'posts' : posts , 'comments' : comment , "form" : form}
        
        return render(request , 'blog/blog-single.html' ,context)
    else:
        return redirect(reverse('accounts:login'))


def blog_home_views(request,**kwargs):
    posts = BlogPost.objects.filter(status=1)
   
    if kwargs.get('blog_category') != None:
        posts = posts.filter(category__name=kwargs['blog_category'])
   
    if kwargs.get('username_author') != None:
        posts = posts.filter(author__username=kwargs['username_author'])
    
    paginator = Paginator(posts, 4)
    page_number = request.GET.get('page')
    
    try:
        posts = paginator.get_page(page_number)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts.paginator.page(paginator.num_pages)
    
    context = {'posts' : posts}
    
    return render(request , 'blog/blog-home.html' ,context)

def blog_search(request):
    # print(request.__dict__)
    posts = BlogPost.objects.filter(status=1)
    if request.method == 'GET':
        # print(request.GET.get('s'))
        if w_s := request.GET.get('s'):  #python walrus
            posts = posts.filter(content__contains=w_s)
        
    
    context = {'posts' : posts}
    return render(request , 'blog/blog-home.html' ,context)















# def test(request ):
    
#     return render(request , 'website/test.html')

# def blog_category(request , blog_category):
#     posts = BlogPost.objects.filter(status=1)
#     posts = posts.filter(category__name=blog_category)
#     context = {'posts' : posts}
#     return render(request , 'blog/blog-home.html' ,context)

templates/blog/ads-widget.html
{% load static %}

<div class="single-sidebar-widget ads-widget">
									<a href="#"><img class="img-fluid" src="{%static 'img/blog/ads-banner.jpg' %}" alt=""></a>
								</div>

templates/blog/blog-home.html
{% extends "base.html" %}
{% load static %}
{% load blog_tags %}
{% load humanize %}
{% block content %}





			<!-- start banner Area -->
			<section class="banner-area relative blog-home-banner" id="home">	
				<div class="overlay overlay-bg"></div>
				<div class="container">				
					<div class="row d-flex align-items-center justify-content-center">
						<div class="about-content blog-header-content col-lg-12">
							<h1 class="text-white">
								Dude You’re Getting
								a Telescope				
							</h1>	
							<p class="text-white">
								There is a moment in the life of any aspiring astronomer that it is time to buy that first
							</p>							
						</div>	
					</div>
				</div>
			</section>
			<!-- End banner Area -->				  

			<!-- Start top-category-widget Area -->
			<section class="top-category-widget-area pt-90 pb-90 ">
				<div class="container">
					<div class="row">		
						<div class="col-lg-4">
							<div class="single-cat-widget">
								<div class="content relative">
									<div class="overlay overlay-bg"></div>
								    <a href="#" target="_blank">
								      <div class="thumb">
								  		 <img class="content-image img-fluid d-block mx-auto" src="{%static 'img/blog/cat-widget1.jpg' %}" alt="">
								  	  </div>
								      <div class="content-details">
								        <h4 class="content-title mx-auto text-uppercase">Social life</h4>
								        <span></span>								        
								        <p>Enjoy your social life together</p>
								      </div>
								    </a>
								</div>
							</div>
						</div>
						<div class="col-lg-4">
							<div class="single-cat-widget">
								<div class="content relative">
									<div class="overlay overlay-bg"></div>
								    <a href="#" target="_blank">
								      <div class="thumb">
								  		 <img class="content-image img-fluid d-block mx-auto" src="{%static 'img/blog/cat-widget2.jpg' %}" alt="">
								  	  </div>
								      <div class="content-details">
								        <h4 class="content-title mx-auto text-uppercase">Politics</h4>
								        <span></span>								        
								        <p>Be a part of politics</p>
								      </div>
								    </a>
								</div>
							</div>
						</div>
						<div class="col-lg-4">
							<div class="single-cat-widget">
								<div class="content relative">
									<div class="overlay overlay-bg"></div>
								    <a href="#" target="_blank">
								      <div class="thumb">
								  		 <img class="content-image img-fluid d-block mx-auto" src="{%static 'img/blog/cat-widget3.jpg' %}" alt="">
								  	  </div>
								      <div class="content-details">
								        <h4 class="content-title mx-auto text-uppercase">Food</h4>
								        <span></span>
								        <p>Let the food be finished</p>
								      </div>
								    </a>
								</div>
							</div>
						</div>												
					</div>
				</div>	
			</section>
			<!-- End top-category-widget Area -->
			
			<!-- Start post-content Area -->
			<section class="post-content-area">
				<div class="container">
					<div class="row">
						<div class="col-lg-8 posts-list">
							{% for post in posts %}
							
							<div class="single-post row">
								<div class="col-lg-3  col-md-3 meta-details">
									
									<ul class="tags">
										{% for cat in post.category.all %}
 											 <li>
												<a href="{%url "blog:category" blog_category=cat.name%}">{{cat.name}}{% if not forloop.last %}, {% endif %}</a>
											 </li>
												{% endfor %}
									</ul>
									
									<div class="user-details row">
										<p class="user-name col-lg-12 col-md-12 col-6"><a href="{%url 'blog:author' username_author=post.author.username%}">{{post.author.get_full_name}}</a> <span class="lnr lnr-user"></span></p>
										<p class="date col-lg-12 col-md-12 col-6"><a href="#">{{post.published_date|naturaltime}}</a> <span class="lnr lnr-calendar-full"></span></p>
										<p class="view col-lg-12 col-md-12 col-6"><a href="#">{{post.counted_view}}</a> <span class="lnr lnr-eye"></span></p>
										<p class="comments col-lg-12 col-md-12 col-6"><a href="#">{%length post.id%} Comments {% comment %} templatetag  {% endcomment %}</a> <span class="lnr lnr-bubble"></span></p>						
									 </div> 
								</div>
								<div class="col-lg-9 col-md-9 ">
									<div class="feature-img">
										<img class="img-fluid" src="{{post.image_filed.url}}" alt="">
									</div>
									<a class="posts-title" href="{% url "blog:blog-single" pid=post.id %}"><h3>{{post.title}}</h3></a>
									<p class="excert">
										
										{{ post.content|truncatechars:200 }}
									</p>
									<a href="{% url "blog:blog-single" pid=post.id %}" class="primary-btn">View More</a>
								</div>
							</div>			
							{% endfor %}								
		                    <nav class="blog-pagination justify-content-center d-flex">
		                        <ul class="pagination">
									{% if posts.has_previous %}
		                            <li class="page-item">
		                                <a href="?page={{ posts.previous_page_number }}" class="page-link" aria-label="Previous">
		                                    <span aria-hidden="true">
		                                        <span class="lnr lnr-chevron-left"></span>
		                                    </span>
		                                </a>
		                            </li>
									{% endif %}
									{% for i  in posts.paginator.page_range %}
									{% if posts.number == i %}
		                            	<li class="page-item active"><a href="?page={{i}}" class="page-link">{{i}}</a></li>
		                            {% else %}
										<li class="page-item"><a href="?page={{i}}" class="page-link">{{i}}</a></li>
		                            {% endif %}
									{% endfor %}
		                            {% if posts.has_next %}
		                            <li class="page-item">
		                                <a href="?page={{ posts.paginator.num_pages }}" class="page-link" aria-label="Next">
		                                    <span aria-hidden="true">
		                                        <span class="lnr lnr-chevron-right"></span>
		                                    </span>
		                                </a>
		                            </li>
									{% endif %}
		                        </ul>
		                    </nav>
						</div>
						<div class="col-lg-4 sidebar-widgets">
							<div class="widget-wrap">
								
								{% include "blog/blog-search.html" %}

								{% include "blog/blog-writer.html" %}
								
								{% categories %}
								

								{% include "blog/popular-post.html" %}
												
							</div>
						</div>
					</div>
				</div>	
			</section>
			<!-- End post-content Area -->
			{% endblock content %}

templates/blog/blog-post-categories.html
{% load static %}
<div class="single-sidebar-widget post-category-widget">
    <h4 class="category-title">Post Catgories</h4>
    <ul class="cat-list">
        {% for name , count in categories.items %}
        <li>
            
            <a href="{%url 'blog:category' blog_category=name%}" class="d-flex justify-content-between">
                <p> {{name}} </p>
                <p>{{count}} </p>
            </a>
        </li>
        {% endfor %}		
    </ul>
</div>	

templates/blog/blog-search.html
{% load static %}



    <div class="single-sidebar-widget search-widget">
        <form class="search-form" action="{%url 'blog:search' %}"  mehtod="get">
            <input placeholder="Search Posts" name="s" type="text" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Search Posts'" >
            <button type="submit"><i class="fa fa-search"></i></button>
        </form>

templates/blog/blog-single.html
{% extends "base.html" %}
{% load blog_tags %}
{% load humanize %}
{% load static %}
{% block content %}

			<!-- start banner Area -->
			<section class="relative about-banner">	
				<div class="overlay overlay-bg"></div>
				<div class="container">				
					<div class="row d-flex align-items-center justify-content-center">
						<div class="about-content col-lg-12">
							<h1 class="text-white">
								{{posts.title}}				
							</h1>	
							<p class="text-white link-nav"><a href="{% url "website:index" %}">Home </a>  <span class="lnr lnr-arrow-right"></span><a href="{% url "blog:blog-home" %}">Blog </a> <span class="lnr lnr-arrow-right"></span>{{posts.title}}</p>
						</div>	
					</div>
				</div>
			</section>
			<!-- End banner Area -->					  
			
			<!-- Start post-content Area -->
			<section class="post-content-area single-post-area">
				<div class="container">
					<div class="row">
						<div class="col-lg-8 posts-list">
							<div class="single-post row">
								<div class="col-lg-12">
									<div class="feature-img">
										<img class="img-fluid" src="{%static 'img/blog/feature-img1.jpg'%}" alt="">
									</div>									
								</div>
								<div class="col-lg-3  col-md-3 meta-details">
									<ul class="tags">
										<li>
											{% for cat in posts.category.all %}
											<a href="#">

											
												{{cat.name}}{% if not forloop.last %}, {% endif %}
									 		

										</a>
										{% endfor %}
									</li>
										
									</ul>
									<div class="user-details row">
										<p class="user-name col-lg-12 col-md-12 col-6"><a href="#">{{posts.author}}</a> <span class="lnr lnr-user"></span></p>
										<p class="date col-lg-12 col-md-12 col-6"><a href="#"> {{ posts.published_date|naturaltime}} </a> <span class="lnr lnr-calendar-full"></span></p>
										<p class="view col-lg-12 col-md-12 col-6"><a href="#">{{posts.counted_view}}</a> <span class="lnr lnr-eye"></span></p>
										<p class="comments col-lg-12 col-md-12 col-6"><a href="#">{{comments|length}} Comments</a> <span class="lnr lnr-bubble"></span></p>
										<ul class="social-links col-lg-12 col-md-12 col-6">
											<li><a href="#"><i class="fa fa-facebook"></i></a></li>
											<li><a href="#"><i class="fa fa-twitter"></i></a></li>
											<li><a href="#"><i class="fa fa-github"></i></a></li>
											<li><a href="#"><i class="fa fa-behance"></i></a></li>
										</ul>																				
									</div>
								</div>
								<div class="col-lg-9 col-md-9">
									<h3 class="mt-20 mb-20">{{posts.title}}</h3>
									<p class="excert">
										{{posts.content|safe}}
									</p>
								
								</div>
							
							</div>
							<div class="navigation-area">
								<div class="row">
									<div class="col-lg-6 col-md-6 col-12 nav-left flex-row d-flex justify-content-start align-items-center">
										<div class="thumb">
											<a href="#"><img class="img-fluid" src="{%static 'img/blog/prev.jpg'%}" alt=""></a>
										</div>
										<div class="arrow">
											<a href="#"><span class="lnr text-white lnr-arrow-left"></span></a>
										</div>
										<div class="detials">
											<p>Prev Post</p>
											<a href="#"><h4>Space The Final Frontier</h4></a>
										</div>
									</div>
									<div class="col-lg-6 col-md-6 col-12 nav-right flex-row d-flex justify-content-end align-items-center">
										<div class="detials">
											<p>Next Post</p>
											<a href="#"><h4>Telescopes 101</h4></a>
										</div>
										<div class="arrow">
											<a href="#"><span class="lnr text-white lnr-arrow-right"></span></a>
										</div>
										<div class="thumb">
											<a href="#"><img class="img-fluid" src="{%static 'img/blog/next.jpg'%}" alt=""></a>
										</div>										
									</div>									
								</div>
							</div>
							<div class="comments-area">
								
								
								<h4>{{comments|length}} Comments</h4>
								<div class="comment-list">
									{% for comment in comments %}
                                    <div class="single-comment justify-content-between d-flex">
                                        <div class="user justify-content-between d-flex">
                                            <div class="thumb">
                                                <img src="{%static 'img/blog/c1.jpg'%}" alt="">
                                            </div>
                                            <div class="desc">
                                                <h5><a href="#">{{comment.name}}</a></h5>
                                                <p class="date">{{comment.create_date|naturaltime}} </p>
                                                <p class="comment">
                                                   {{comment.message}}
                                                </p>
                                            </div>
                                        </div>


                                        {% comment %} <div class="reply-btn">
                                               <a href="" class="btn-reply text-uppercase">reply</a> 
                                        </div> {% endcomment %}
                                    
									</div>
									{% endfor %}    
                                </div>	
								
								                                 				
							</div>
							<div class="comment-form">
								<h4>Leave a Comment</h4>
								<form method='POST' action='{% url "blog:blog-single" pid=posts.id %}'>
									{% csrf_token %}
									<input type="hidden" name='post' value="{{posts.id}}"  >
									{% if request.user.is_authenticated %}
									<input type="hidden" name='name' value="{{request.user.username}}"  >
									<input type="hidden" name='email' value="{{request.user.email}}"  >
									
									{% else %}
									<div class="form-group form-inline">
										<div class="form-group col-lg-6 col-md-12 name">
										  <input type="text" name='name'  class="form-control" id="name" placeholder="Enter Name" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Name'">
										</div>
										<div class="form-group col-lg-6 col-md-12 email">
										  <input type="email" name='email' class="form-control" id="email" placeholder="Enter email address" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter email address'">
										</div>										
									  </div>
									  {% endif %}
									  <div class="form-group">
										  <input type="text" name='subject' class="form-control" id="subject" placeholder="Subject" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Subject'">
									  </div>
									  <div class="form-group">
										  <textarea class="form-control mb-10" rows="5" name="message" placeholder="Messege" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Messege'" required=""></textarea>
									  </div>
									  
									  <button type="submit" class="primary-btn text-uppercase">Post Comment</button>	
									 
									</form>
							</div>
						</div>
						<div class="col-lg-4 sidebar-widgets">

							
								
								{% include "blog/blog-writer.html" %}
								
								{% include "blog/widget-wrap.html" %}
							
								
								
								{% include "blog/ads-widget.html" %}
								
							</div>
						</div>
					</div>
				</div>	
			</section>
			<!-- End post-content Area -->
		{% endblock content %}

templates/blog/blog-writer.html
{% load static %}

<div class="single-sidebar-widget user-info-widget">
    <img src="{%static 'img/blog/user-info.png' %}" alt="">
    <a href="#"><h4>Erfan Razavi</h4></a>
    <p>
        Senior blog writer
    </p>
    <ul class="social-links">
        <li><a href="#"><i class="fa fa-facebook"></i></a></li>
        <li><a href="#"><i class="fa fa-twitter"></i></a></li>
        <li><a href="#"><i class="fa fa-github"></i></a></li>
        <li><a href="#"><i class="fa fa-behance"></i></a></li>
    </ul>
    <p>
        Boot camps have its supporters andit sdetractors. Some people do not understand why you should have to spend money on boot camp when you can get. Boot camps have itssuppor ters andits detractors.
    </p>
</div>

templates/blog/popular-post.html
{% load static %}
{% load humanize %}

								<div class="single-sidebar-widget popular-post-widget">
									<h4 class="popular-title">Popular Posts</h4>
                                    
									<div class="popular-post-list">
                                         {%for post in posts %}
										<div class="single-post-list d-flex flex-row align-items-center">
											<div class="thumb">
												<img class="img-fluid" src="{{post.image.url}}" alt="">
											</div>
											<div class="details">
												<a href="{% url "blog:blog-single" pid=post.id %}"><h6>{{post.title}}</h6></a>
												<p>{{post.published_date|naturaltime}}</p>
											</div>
										</div>
										{% endfor %}
                                        														
									</div>
                                    
								</div>
					

templates/blog/widget-wrap.html
{% load static %}
<div class="widget-wrap">
    <div class="single-sidebar-widget search-widget">
        <form class="search-form" action="#">
            <input placeholder="Search Posts" name="search" type="text" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Search Posts'" >
            <button type="submit"><i class="fa fa-search"></i></button>
        </form>
    </div>